### ISSUE TITLE
Are you still active?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [Whales/Cataclysm2#54]
Hello @Whales.

Are you still posting public code to GitHub?

**Comment by Whales** [comment]
Nope

**Comment by BorkBorkGoesTheCode** [comment]
Okay. Do you mind receiving non-spam communications?

**Comment by Whales** [comment]
Not at all! Feel free to email me directly at fivedozenwhales@gmail.com.
I'm happy to help with anything.
